# Generated by Django 4.1 on 2022-08-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_hackernews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HackerNews',
        ),
    ]
